"""Search-text and embedding-input builders for v2 chunks.

The v2 pipeline leaves chunk_context empty (NULL). What remains here are
two pure helpers that derive per-chunk strings from the JSONB chunk_text:

- build_search_text: lowercased, punctuation-stripped flat string used as
  the source of the GENERATED search_vector (BM25). Order: optional
  context, then deduped speaker short-names, then all utterance text.

- build_embedding_input: conversational format passed to the embedder.
  Lines are `<sn>: <text>` per turn, no timestamps, no JSON wrapping.
  When chunk_context is provided it appears as a "Context: ..." preamble.

This module also retains _get_client() and _llm_deployment() for use by
other services (insights generation, MOM summary). The previous LLM-based
contextualization (_batch_topic_sentences and contextualize_chunks) has
been removed — chunk_context is generated by no one in v2.
"""
from __future__ import annotations

import logging
import re

from openai import AsyncAzureOpenAI

from app.config.settings import get_settings

log = logging.getLogger(__name__)

_PUNCT_RE = re.compile(r"[^\w\s]+")
_WS_RE = re.compile(r"\s+")

_client: AsyncAzureOpenAI | None = None


def _get_client() -> AsyncAzureOpenAI:
    """Lazy module-level Azure OpenAI async client (used by insights + summary)."""
    global _client
    if _client is None:
        s = get_settings()
        _client = AsyncAzureOpenAI(
            api_key=s.AZURE_OPENAI_API_KEY,
            azure_endpoint=s.AZURE_OPENAI_ENDPOINT,
            api_version="2024-02-01",
        )
    return _client


def _llm_deployment() -> str:
    """Mini deployment if configured, else the main LLM (used by insights + summary)."""
    s = get_settings()
    return s.AZURE_OPENAI_DEPLOYMENT_LLM_MINI or s.AZURE_OPENAI_DEPLOYMENT_LLM


def build_search_text(
    chunk_text: list[dict],
    chunk_context: str | None = None,
) -> str:
    """Produce the BM25-bound flat string for a chunk.

    Format (lowercased, punctuation stripped, single-spaced):
        [<chunk_context>] <sn1> <sn2> ... <utterance text 1> <utterance text 2> ...

    chunk_context is included only when non-null. Speakers are emitted before
    text so a query like "what did Ashish say about pricing" matches both
    the speaker token and content tokens.
    """
    parts: list[str] = []
    if chunk_context:
        parts.append(chunk_context)

    seen_sn: set[str] = set()
    for turn in chunk_text:
        sn = turn.get("sn", "")
        if sn and sn not in seen_sn:
            parts.append(sn)
            seen_sn.add(sn)

    for turn in chunk_text:
        t = turn.get("t", "")
        if t:
            parts.append(t)

    raw = " ".join(parts).lower()
    raw = _PUNCT_RE.sub(" ", raw)
    return _WS_RE.sub(" ", raw).strip()


def build_embedding_input(
    chunk_text: list[dict],
    chunk_context: str | None = None,
) -> str:
    """Produce the conversational embedding input for a chunk.

    Format:
        Context: <chunk_context>      (only when non-null)

        <sn>: <text>
        <sn>: <text>
        ...

    No timestamps, no JSON, no metadata prefix beyond the optional context line.
    Speaker short-names (sn) keep the input compact while still letting the
    embedding model learn per-speaker patterns.
    """
    lines: list[str] = []
    if chunk_context:
        lines.append(f"Context: {chunk_context}")
        lines.append("")

    for turn in chunk_text:
        sn = turn.get("sn") or "Unknown"
        t = turn.get("t", "")
        lines.append(f"{sn}: {t}")

    return "\n".join(lines)
